import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={inter.className}>
          <Navbar/>
          {children}
        </main>
        
      </body>
    </html>
  )
}
